"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useContext, createContext } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const ThemeContext = createContext(null);
export const ThemeProvider = ({
  children,
  value,
}: {
  children: any;
  value: any;
}) => {
  return (
    <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>
  );
};
const useTheme = () => {
  return useContext(ThemeContext);
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = localStorage.getItem("theme");
  console.log(theme);

  return (
    <html lang="en">
      <ThemeProvider value={theme}>
        <body className={inter.className}>
          <main>{children}</main>
        </body>
      </ThemeProvider>
    </html>
  );
}
